/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;
import gui.InvoiceForm;
import gui.DashboardForm;

/**
 *
 * @author chela
 */
public class OrderForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderForm.class.getName());

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadCustomersToCombo();
        loadMenuItemsByFoodType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbMenuItem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtOrderQuantity = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnClearOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbFilterFoodType = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer");

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Menu Item");

        cmbMenuItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Quantity");

        btnAddToCart.setBackground(new java.awt.Color(255, 0, 0));
        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("Add to cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        btnPlaceOrder.setBackground(new java.awt.Color(255, 0, 0));
        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnClearOrder.setBackground(new java.awt.Color(255, 0, 0));
        btnClearOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnClearOrder.setText("Clear");
        btnClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Grand Total");

        txtGrandTotal.setEditable(false);

        jLabel5.setText("Food Type");

        cmbFilterFoodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Veg", "Non-Veg", "Beverage", "Dessert", "Spicy", "Special" }));
        cmbFilterFoodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterFoodTypeActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveItem.setBackground(new java.awt.Color(255, 0, 0));
        btnRemoveItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveItem.setText("Remove from cart");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilterFoodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnAddToCart)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearOrder))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlaceOrder)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbFilterFoodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart)
                    .addComponent(btnClearOrder)
                    .addComponent(btnRemoveItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlaceOrder))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        try {
            String selectedItem = cmbMenuItem.getSelectedItem().toString();
            int quantity = Integer.parseInt(txtOrderQuantity.getText());

            String[] itemParts = selectedItem.split(" - ");
            int itemId = Integer.parseInt(itemParts[0]);
            String itemName = itemParts[1];

            Connection con = DBConnection.getConnection();
            String sql = "SELECT price, quantity FROM menu_items WHERE item_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, itemId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                double unitPrice = rs.getDouble("price");
                double total = unitPrice * quantity;

                DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
                model.addRow(new Object[]{
                    itemId,
                    itemName,
                    quantity,
                    unitPrice,
                    total
                });

                calculateGrandTotal();
                txtOrderQuantity.setText("");
            }
            int availableQty = rs.getInt("quantity");

            if (quantity > availableQty) {
                JOptionPane.showMessageDialog(this, "Not enough stock available!");
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        try {
            String selectedCustomer = cmbCustomer.getSelectedItem().toString();
            String[] customerParts = selectedCustomer.split(" - ");
            int customerId = Integer.parseInt(customerParts[0]);

            LocalDate orderDate = LocalDate.now();
            LocalTime orderTime = LocalTime.now();

            double grandTotal = Double.parseDouble(txtGrandTotal.getText());
            double subtotal = grandTotal;
            double discount = 0.0;

            Connection con = DBConnection.getConnection();

            String orderSql = "INSERT INTO orders(customer_id, order_date, order_time, subtotal, discount, grand_total) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement orderPst = con.prepareStatement(orderSql, Statement.RETURN_GENERATED_KEYS);

            orderPst.setInt(1, customerId);
            orderPst.setDate(2, java.sql.Date.valueOf(orderDate));
            orderPst.setTime(3, java.sql.Time.valueOf(orderTime));
            orderPst.setDouble(4, subtotal);
            orderPst.setDouble(5, discount);
            orderPst.setDouble(6, grandTotal);

            orderPst.executeUpdate();

            ResultSet generatedKeys = orderPst.getGeneratedKeys();
            int orderId = 0;

            if (generatedKeys.next()) {
                orderId = generatedKeys.getInt(1);
            }

            DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                int itemId = Integer.parseInt(model.getValueAt(i, 0).toString());
                int quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
                double unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());
                double totalPrice = Double.parseDouble(model.getValueAt(i, 4).toString());

                String itemSql = "INSERT INTO order_items(order_id, item_id, quantity, unit_price, total_price) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement itemPst = con.prepareStatement(itemSql);

                itemPst.setInt(1, orderId);
                itemPst.setInt(2, itemId);
                itemPst.setInt(3, quantity);
                itemPst.setDouble(4, unitPrice);
                itemPst.setDouble(5, totalPrice);

                itemPst.executeUpdate();
                String updateStockSql = "UPDATE menu_items SET quantity = quantity - ? WHERE item_id = ?";
                PreparedStatement stockPst = con.prepareStatement(updateStockSql);
                stockPst.setInt(1, quantity);
                stockPst.setInt(2, itemId);
                stockPst.executeUpdate();
            }

            StringBuilder invoice = new StringBuilder();

            invoice.append("        ISLAND FLAVORS RESTAURANT\n");
            invoice.append("========================================\n");
            invoice.append("Order ID: ").append(orderId).append("\n");
            invoice.append("Customer: ").append(selectedCustomer).append("\n");
            invoice.append("Date: ").append(orderDate).append("\n");
            invoice.append("Time: ").append(orderTime.withNano(0)).append("\n");
            invoice.append("========================================\n");
            invoice.append(String.format("%-15s %-8s %-10s\n", "Item", "Qty", "Total"));
            invoice.append("========================================\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0) == null) {
                    continue;
                }

                String itemName = model.getValueAt(i, 1).toString();
                String qty = model.getValueAt(i, 2).toString();
                String total = model.getValueAt(i, 4).toString();

                invoice.append(String.format("%-15s %-8s %-10s\n", itemName, qty, total));
            }

            invoice.append("========================================\n");
            invoice.append("Grand Total: ").append(grandTotal).append("\n");
            invoice.append("========================================\n");
            invoice.append("      Thank you for visiting us!\n");

            InvoiceForm invoiceForm = new InvoiceForm(invoice.toString());
            invoiceForm.setVisible(true);

            JOptionPane.showMessageDialog(this, "Order placed successfully!");

            ((DefaultTableModel) tblOrder.getModel()).setRowCount(0);
            txtGrandTotal.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderActionPerformed
        txtOrderQuantity.setText("");
        txtGrandTotal.setText("");
        ((DefaultTableModel) tblOrder.getModel()).setRowCount(0);
    }//GEN-LAST:event_btnClearOrderActionPerformed

    private void cmbFilterFoodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterFoodTypeActionPerformed
        loadMenuItemsByFoodType();
    }//GEN-LAST:event_cmbFilterFoodTypeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DashboardForm dashboard = new DashboardForm();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        int selectedRow = tblOrder.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.removeRow(selectedRow);

        calculateGrandTotal();
    }//GEN-LAST:event_btnRemoveItemActionPerformed
    
    public void loadMenuItemsByFoodType() {
        try {
            Connection con = DBConnection.getConnection();

            String selectedType = cmbFilterFoodType.getSelectedItem().toString();
            String sql;

            if (selectedType.equals("All")) {
                sql = "SELECT item_id, item_name FROM menu_items";
            } else {
                sql = "SELECT item_id, item_name FROM menu_items WHERE food_type = ?";
            }

            PreparedStatement pst = con.prepareStatement(sql);

            if (!selectedType.equals("All")) {
                pst.setString(1, selectedType);
            }

            ResultSet rs = pst.executeQuery();

            cmbMenuItem.removeAllItems();

            while (rs.next()) {
                cmbMenuItem.addItem(rs.getInt("item_id") + " - " + rs.getString("item_name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }    
    
    public void calculateGrandTotal() {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        double grandTotal = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 4);

            if (value != null) {
                grandTotal += Double.parseDouble(value.toString());
            }
        }

        txtGrandTotal.setText(String.valueOf(grandTotal));
    }
    
    
    public void loadCustomersToCombo() {
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT customer_id, customer_name FROM customers";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cmbCustomer.removeAllItems();

            while (rs.next()) {
                cmbCustomer.addItem(rs.getInt("customer_id") + " - " + rs.getString("customer_name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public void loadMenuItemsToCombo() {
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT item_id, item_name FROM menu_items";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cmbMenuItem.removeAllItems();

            while (rs.next()) {
                cmbMenuItem.addItem(rs.getInt("item_id") + " - " + rs.getString("item_name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearOrder;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbFilterFoodType;
    private javax.swing.JComboBox<String> cmbMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtOrderQuantity;
    // End of variables declaration//GEN-END:variables
}
